
services:
  web:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
      - .:/var/www/
    working_dir: /var/www
###> doctrine/doctrine-bundle ###
  database:
    image: docker.io/mariadb:11.5
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: app
    ports:
      - "8306:3306"
    volumes:
      - database_data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
