
services:
  web:
    build:
      dockerfile: ./Dockerfile
    command:
      - apache2-foreground
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
      - .:/var/www/
      - symfony_cache:/var/www/var/cache
      - symfony_log:/var/www/var/log
      - symfony_sessions:/var/www/var/sessions
    working_dir: /var/www
  worker:
    build:
      dockerfile: ./Dockerfile
    command:
      - php
      - bin/console
      - messenger:consume
      - async
      - --time-limit=3600
      - --memory-limit=128M
      - --no-interaction
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    init: true
    restart: unless-stopped
    volumes:
      - .:/var/www/
      - symfony_cache:/var/www/var/cache
      - symfony_log:/var/www/var/log
      - symfony_sessions:/var/www/var/sessions
    working_dir: /var/www
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
###> doctrine/doctrine-bundle ###
  database:
    image: docker.io/mariadb:11.5
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: app
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    ports:
      - "8306:3306"
    volumes:
      - database_data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  redis_data:
  symfony_cache:
  symfony_log:
  symfony_sessions:
